import 'controller/cancel_booking_controller.dart';import 'package:flutter/material.dart';import 'package:hotelapp/core/app_export.dart';import 'package:hotelapp/widgets/custom_button.dart';
// ignore_for_file: must_be_immutable
class CancelBookingBottomsheet extends StatelessWidget {CancelBookingBottomsheet(this.controller);

CancelBookingController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: size.width, padding: getPadding(left: 24, top: 8, right: 24, bottom: 8), decoration: AppDecoration.outlineGray8002.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomImageView(svgPath: ImageConstant.imgFrameGray700, height: getVerticalSize(3.00), width: getHorizontalSize(38.00)), Padding(padding: getPadding(top: 26), child: Text("lbl_cancel_booking".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold24RedA200)), Container(width: getHorizontalSize(340.00), margin: getMargin(top: 26), child: Text("msg_are_you_sure_yo2".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtUrbanistRomanBold20)), Container(width: getHorizontalSize(372.00), margin: getMargin(top: 8), child: Text("msg_only_80_of_the".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtUrbanistRegular14WhiteA700.copyWith(letterSpacing: getHorizontalSize(0.20)))), Padding(padding: getPadding(top: 22, bottom: 58), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomButton(height: 58, width: 184, text: "lbl_cancel".tr, variant: ButtonVariant.FillGray800), CustomButton(height: 58, width: 184, text: "lbl_continue".tr, variant: ButtonVariant.OutlineGreenA7003f, onTap: onTapContinue)]))]))); } 
onTapContinue() { Get.toNamed(AppRoutes.refundMethodScreen); } 
 }
